// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdjwfeewjvmujyarftkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkandmZWV3anZtdWp5YXJmdGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzgzNjAsImV4cCI6MjA2NjcxNDM2MH0.lF57upnCjHvkJWdKefKeE_vVgYxbCuPXs4O4LoxSyvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);